#!/bin/sh
cd "${0%/*}" || exit 1                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
cleanCase

# this was the original Allclean script for icofoam cases
#eepCases="cavity cavityGrade cavityClipped"
#loseCases="cavityFine cavityHighRe"

#for caseName in $keepCases
#do
#    ( cd $caseName && foamCleanTutorials )
#done

#for caseName in $loseCases
#do
#    removeCase $caseName
#done

#------------------------------------------------------------------------------
